name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:
    inputs:
      only-update-submodules:
        type: boolean

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.commit.outputs.commit_hash }}
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Update submodules
        run: |
          git submodule status
          git submodule update --init --remote
      - name: Commit and Push Changes
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Updated submodules"
  build:
    runs-on: ubuntu-latest
    needs: update-submodules
    if: ${{ inputs.only-update-submodules == false || inputs.only-update-submodules == 'false' }}
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: ${{ needs.update-submodules.outputs.commit_hash == '' && 'main' || needs.update-submodules.outputs.commit_hash }}
      - name: Make fetch_gtag.sh executable
        run: chmod +x fetch_gtag.sh
      - name: Fetch gtag.js
        run: ./fetch_gtag.sh
      - name: Install, build, and upload your site
        uses: withastro/action@v2
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ inputs.only-update-submodules == false || inputs.only-update-submodules == 'false' }}
    environment:
      name: github-pages
      url: https://pompeybug.co.uk
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
