name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:
    inputs:
      only-update-submodules:
        type: boolean

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          submodules: recursive
      - name: Update submodules to remote HEAD
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git submodule update --init --remote
          if git diff --quiet; then
            echo "No submodule changes"
          else
            git add src/content
            git commit -m "Update submodules to latest"
            git pull --rebase origin main
            git push origin HEAD:main
          fi
  build:
    runs-on: ubuntu-latest
    needs: update-submodules
    if: ${{ inputs.only-update-submodules == false || inputs.only-update-submodules == 'false' }}
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Make fetch_gtag.sh executable
        run: chmod +x fetch_gtag.sh
      - name: Fetch gtag.js
        run: ./fetch_gtag.sh
      - name: Install, build, and upload your site
        uses: withastro/action@v2
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ inputs.only-update-submodules == false || inputs.only-update-submodules == 'false' }}
    environment:
      name: github-pages
      url: https://pompeybug.co.uk
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
